/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExamplesRouteImport } from './routes/examples'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortfolioForDesignersRouteImport } from './routes/portfolio-for-designers'
import { Route as PortfolioForDevelopersRouteImport } from './routes/portfolio-for-developers'
import { Route as PortfolioForFreelancersRouteImport } from './routes/portfolio-for-freelancers'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResumeToPortfolioRouteImport } from './routes/resume-to-portfolio'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAiStructureRouteImport } from './routes/api.ai-structure'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as LocalSlugRouteImport } from './routes/local.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRoute = ExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioForDesignersRoute = PortfolioForDesignersRouteImport.update({
  id: '/portfolio-for-designers',
  path: '/portfolio-for-designers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioForDevelopersRoute = PortfolioForDevelopersRouteImport.update({
  id: '/portfolio-for-developers',
  path: '/portfolio-for-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioForFreelancersRoute = PortfolioForFreelancersRouteImport.update({
  id: '/portfolio-for-freelancers',
  path: '/portfolio-for-freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeToPortfolioRoute = ResumeToPortfolioRouteImport.update({
  id: '/resume-to-portfolio',
  path: '/resume-to-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiStructureRoute = ApiAiStructureRouteImport.update({
  id: '/api/ai-structure',
  path: '/api/ai-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/guides/$slug',
  path: '/guides/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSlugRoute = LocalSlugRouteImport.update({
  id: '/local/$slug',
  path: '/local/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portfolio-for-designers': typeof PortfolioForDesignersRoute
  '/portfolio-for-developers': typeof PortfolioForDevelopersRoute
  '/portfolio-for-freelancers': typeof PortfolioForFreelancersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/ai-structure': typeof ApiAiStructureRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/local/$slug': typeof LocalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portfolio-for-designers': typeof PortfolioForDesignersRoute
  '/portfolio-for-developers': typeof PortfolioForDevelopersRoute
  '/portfolio-for-freelancers': typeof PortfolioForFreelancersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/ai-structure': typeof ApiAiStructureRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/local/$slug': typeof LocalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/guides': typeof GuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/dashboard': typeof DashboardRoute
  '/examples': typeof ExamplesRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/portfolio-for-designers': typeof PortfolioForDesignersRoute
  '/portfolio-for-developers': typeof PortfolioForDevelopersRoute
  '/portfolio-for-freelancers': typeof PortfolioForFreelancersRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resume-to-portfolio': typeof ResumeToPortfolioRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRoute
  '/terms': typeof TermsRoute
  '/api/ai-structure': typeof ApiAiStructureRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/local/$slug': typeof LocalSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/guides/': typeof GuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/examples'
    | '/features'
    | '/login'
    | '/portfolio-for-designers'
    | '/portfolio-for-developers'
    | '/portfolio-for-freelancers'
    | '/pricing'
    | '/privacy'
    | '/resume-to-portfolio'
    | '/signup'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/api/ai-structure'
    | '/guides/$slug'
    | '/local/$slug'
    | '/p/$slug'
    | '/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/examples'
    | '/features'
    | '/login'
    | '/portfolio-for-designers'
    | '/portfolio-for-developers'
    | '/portfolio-for-freelancers'
    | '/pricing'
    | '/privacy'
    | '/resume-to-portfolio'
    | '/signup'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/api/ai-structure'
    | '/guides/$slug'
    | '/local/$slug'
    | '/p/$slug'
    | '/guides'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/dashboard'
    | '/examples'
    | '/features'
    | '/login'
    | '/portfolio-for-designers'
    | '/portfolio-for-developers'
    | '/portfolio-for-freelancers'
    | '/pricing'
    | '/privacy'
    | '/resume-to-portfolio'
    | '/signup'
    | '/sitemap.xml'
    | '/templates'
    | '/terms'
    | '/api/ai-structure'
    | '/guides/$slug'
    | '/local/$slug'
    | '/p/$slug'
    | '/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardRoute: typeof DashboardRoute
  ExamplesRoute: typeof ExamplesRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PortfolioForDesignersRoute: typeof PortfolioForDesignersRoute
  PortfolioForDevelopersRoute: typeof PortfolioForDevelopersRoute
  PortfolioForFreelancersRoute: typeof PortfolioForFreelancersRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResumeToPortfolioRoute: typeof ResumeToPortfolioRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRoute
  TermsRoute: typeof TermsRoute
  ApiAiStructureRoute: typeof ApiAiStructureRoute
  GuidesSlugRoute: typeof GuidesSlugRoute
  LocalSlugRoute: typeof LocalSlugRoute
  PSlugRoute: typeof PSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples': {
      id: '/examples'
      path: '/examples'
      fullPath: '/examples'
      preLoaderRoute: typeof ExamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-for-designers': {
      id: '/portfolio-for-designers'
      path: '/portfolio-for-designers'
      fullPath: '/portfolio-for-designers'
      preLoaderRoute: typeof PortfolioForDesignersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-for-developers': {
      id: '/portfolio-for-developers'
      path: '/portfolio-for-developers'
      fullPath: '/portfolio-for-developers'
      preLoaderRoute: typeof PortfolioForDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-for-freelancers': {
      id: '/portfolio-for-freelancers'
      path: '/portfolio-for-freelancers'
      fullPath: '/portfolio-for-freelancers'
      preLoaderRoute: typeof PortfolioForFreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-to-portfolio': {
      id: '/resume-to-portfolio'
      path: '/resume-to-portfolio'
      fullPath: '/resume-to-portfolio'
      preLoaderRoute: typeof ResumeToPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-structure': {
      id: '/api/ai-structure'
      path: '/api/ai-structure'
      fullPath: '/api/ai-structure'
      preLoaderRoute: typeof ApiAiStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/guides/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/$slug': {
      id: '/local/$slug'
      path: '/local/$slug'
      fullPath: '/local/$slug'
      preLoaderRoute: typeof LocalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardRoute: DashboardRoute,
  ExamplesRoute: ExamplesRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PortfolioForDesignersRoute: PortfolioForDesignersRoute,
  PortfolioForDevelopersRoute: PortfolioForDevelopersRoute,
  PortfolioForFreelancersRoute: PortfolioForFreelancersRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResumeToPortfolioRoute: ResumeToPortfolioRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRoute,
  TermsRoute: TermsRoute,
  ApiAiStructureRoute: ApiAiStructureRoute,
  GuidesSlugRoute: GuidesSlugRoute,
  LocalSlugRoute: LocalSlugRoute,
  PSlugRoute: PSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
