export type PortfolioTemplate = {
  id: string;
  name: string;
  category: string;
  description: string;
  premium: boolean;
  accent: string;
  layout: string;
  recommendedFor?: string[];
};

// Keep in sync with the frontend catalog (portfolio-builder/src/lib/template-catalog.ts),
// which owns how each template looks. This list decides which templates can be
// saved, and `premium` decides which can be published (see portfolio-access.ts).
export const portfolioTemplates: PortfolioTemplate[] = [
  {
    id: "clean-professional",
    name: "Clean Professional",
    category: "Universal",
    description: "A composed, editorial portfolio for every kind of professional.",
    premium: false,
    accent: "#2f6fed",
    layout: "clean",
    recommendedFor: ["Developer","Product Manager","Consultant","Teacher"],
  },
  {
    id: "developer-command-center",
    name: "Developer Command Center",
    category: "Software Engineering",
    description: "A focused dark canvas for technical work, systems thinking, and shipped projects.",
    premium: true,
    accent: "#77e6c0",
    layout: "developer",
    recommendedFor: ["Software Developer","AI Engineer","Data Scientist"],
  },
  {
    id: "plain-text",
    name: "Plain Text",
    category: "Software Engineering",
    description: "A quiet, text-first page set in monospace. Nothing distracts from the work.",
    premium: false,
    accent: "#b93a0b",
    layout: "minimal",
    recommendedFor: ["Software Developer","Backend Engineer","Open-source Maintainer"],
  },
  {
    id: "tech-lead",
    name: "Tech Lead",
    category: "Software Engineering",
    description: "A leadership-first layout that puts scope, teams, and outcomes up front.",
    premium: true,
    accent: "#0f766e",
    layout: "executive",
    recommendedFor: ["Engineering Manager","Tech Lead","Staff Engineer"],
  },
  {
    id: "frontend-studio",
    name: "Frontend Studio",
    category: "Frontend & Mobile",
    description: "A split-screen layout with a bold color panel and room for polished UI work.",
    premium: false,
    accent: "#4f46e5",
    layout: "split",
    recommendedFor: ["Frontend Developer","Mobile Developer","UI Engineer"],
  },
  {
    id: "app-showcase",
    name: "App Showcase",
    category: "Frontend & Mobile",
    description: "Project-first cards with vivid covers, made for shipped apps and side projects.",
    premium: true,
    accent: "#0369a1",
    layout: "gallery",
    recommendedFor: ["Mobile Developer","Product Engineer","Indie Hacker"],
  },
  {
    id: "research-scientist",
    name: "Research Scientist",
    category: "Data & AI",
    description: "A classic CV layout with serif typography, suited to research and publications.",
    premium: false,
    accent: "#1d4ed8",
    layout: "academic",
    recommendedFor: ["Data Scientist","Researcher","ML Engineer"],
  },
  {
    id: "neural",
    name: "Neural",
    category: "Data & AI",
    description: "A dark, gradient-lit canvas for AI and machine-learning work.",
    premium: true,
    accent: "#a78bfa",
    layout: "creative",
    recommendedFor: ["AI Engineer","ML Researcher","Data Scientist"],
  },
  {
    id: "cloud-console",
    name: "Cloud Console",
    category: "Cloud & Security",
    description: "A console-style sidebar layout for infrastructure, reliability, and platform work.",
    premium: false,
    accent: "#f97316",
    layout: "sidebar",
    recommendedFor: ["DevOps Engineer","Cloud Architect","SRE"],
  },
  {
    id: "secure-shell",
    name: "Secure Shell",
    category: "Cloud & Security",
    description: "A hardened terminal aesthetic in red and amber for security work.",
    premium: true,
    accent: "#f87171",
    layout: "developer",
    recommendedFor: ["Security Engineer","Penetration Tester","SOC Analyst"],
  },
  {
    id: "bento-professional",
    name: "Bento Professional",
    category: "Design & Creative",
    description: "An expressive modular layout for people with a range of work to show.",
    premium: true,
    accent: "#d87852",
    layout: "bento",
    recommendedFor: ["Designer","Product Manager","Consultant","Marketing Professional"],
  },
  {
    id: "gallery",
    name: "Gallery",
    category: "Design & Creative",
    description: "A project-first grid with bold covers, for visual work that lives behind a link.",
    premium: false,
    accent: "#0a0a0a",
    layout: "gallery",
    recommendedFor: ["Designer","Photographer","Illustrator"],
  },
  {
    id: "swiss",
    name: "Swiss",
    category: "Design & Creative",
    description: "Grid-true Swiss typography in black, white, and a single red.",
    premium: false,
    accent: "#d0021b",
    layout: "minimal",
    recommendedFor: ["Graphic Designer","Brand Designer","Art Director"],
  },
  {
    id: "editorial",
    name: "Editorial",
    category: "Writing & Content",
    description: "Magazine-style typography with a serif masthead, made for writers and storytellers.",
    premium: false,
    accent: "#b91c1c",
    layout: "editorial",
    recommendedFor: ["Writer","Journalist","Content Strategist"],
  },
  {
    id: "growth",
    name: "Growth",
    category: "Marketing & Sales",
    description: "A confident split layout in warm orange for marketers who measure what they ship.",
    premium: false,
    accent: "#c2410c",
    layout: "split",
    recommendedFor: ["Marketing Professional","Growth Marketer","Sales Lead"],
  },
  {
    id: "bold-studio",
    name: "Bold Studio",
    category: "Marketing & Sales",
    description: "Oversized type on a dark stage with a lime accent. Loud, in a good way.",
    premium: true,
    accent: "#d9f99d",
    layout: "creative",
    recommendedFor: ["Creative Director","Brand Strategist","Content Creator"],
  },
  {
    id: "executive",
    name: "Executive",
    category: "Business & Consulting",
    description: "Formal and assured: a navy masthead, gold details, and a leadership-first structure.",
    premium: false,
    accent: "#a16207",
    layout: "executive",
    recommendedFor: ["Consultant","Executive","Operations Leader"],
  },
  {
    id: "freelance-studio",
    name: "Freelance Studio",
    category: "Business & Consulting",
    description: "Soft pastel tiles that make services, clients, and contact details easy to scan.",
    premium: true,
    accent: "#a78bfa",
    layout: "bento",
    recommendedFor: ["Freelancer","Consultant","Small Business Owner"],
  },
  {
    id: "ledger",
    name: "Ledger",
    category: "Business & Consulting",
    description: "An ivory and forest-green resume layout with the calm precision finance roles need.",
    premium: true,
    accent: "#166534",
    layout: "sidebar",
    recommendedFor: ["Accountant","Financial Analyst","Banker"],
  },
  {
    id: "educator",
    name: "Educator",
    category: "Education",
    description: "A friendly career timeline that tells your teaching story, class by class.",
    premium: false,
    accent: "#0f766e",
    layout: "timeline",
    recommendedFor: ["Teacher","Tutor","Instructional Designer"],
  },
  {
    id: "academic-cv",
    name: "Academic CV",
    category: "Education",
    description: "A traditional academic CV with small-caps headings and print-ready structure.",
    premium: true,
    accent: "#7c2d12",
    layout: "academic",
    recommendedFor: ["Researcher","Lecturer","PhD Candidate"],
  },
  {
    id: "care-team",
    name: "Care Team",
    category: "Healthcare",
    description: "A calm, clinically clean resume layout for healthcare professionals.",
    premium: false,
    accent: "#0e7490",
    layout: "sidebar",
    recommendedFor: ["Nurse","Physician","Healthcare Administrator"],
  },
  {
    id: "impact",
    name: "Impact",
    category: "Law & Public Service",
    description: "A mission-driven timeline for public service, policy, and nonprofit careers.",
    premium: false,
    accent: "#15803d",
    layout: "timeline",
    recommendedFor: ["Nonprofit Professional","Policy Analyst","Community Organizer"],
  },
  {
    id: "counsel",
    name: "Counsel",
    category: "Law & Public Service",
    description: "A formal serif layout in burgundy, suited to legal and advisory careers.",
    premium: true,
    accent: "#7f1d1d",
    layout: "editorial",
    recommendedFor: ["Lawyer","Paralegal","Compliance Officer"],
  },
];

export const getTemplate = (id: string) =>
  portfolioTemplates.find((template) => template.id === id);
