import { ArrowUpRight, Github, Mail, Code2, MapPin } from 'lucide-react';
import './portfolio-mini.css';

export type MiniStyle = 'clean-professional' | 'developer-command-center' | 'bento-professional';
export function PortfolioMini({ templateId = 'clean-professional', expanded = false }: { templateId?: string; expanded?: boolean }) {
  const developer = templateId === 'developer-command-center';
  const bento = templateId === 'bento-professional';
  return <div className={`portfolio-mini ${developer ? 'mini-developer' : bento ? 'mini-bento' : 'mini-professional'} ${expanded ? 'mini-expanded' : ''}`} aria-label={`Sample ${developer ? 'developer' : bento ? 'creative' : 'professional'} portfolio`}>
    <div className="mini-nav"><span className="mini-monogram">{developer ? '<JL />' : bento ? 'maya.' : 'Alex Morgan'}<span className="mini-dot" /></span><span className="mini-nav-items">Work <span>About</span> <span>Contact</span></span><ArrowUpRight size={13} /></div>
    {developer ? <>
      <div className="mini-code-hero"><div><span className="mini-available"><i /> Open to opportunities</span><h3>Building things<br />that make<br /><strong>a difference.</strong></h3><p>Jordan Lee · Full-stack developer</p><span className="mini-work-button">Explore my projects <ArrowUpRight size={12} /></span></div><div className="mini-code"><div><i /><i /><i /><span>about.ts</span></div><pre><span>const</span> developer = {'{'}<br />  name: <b>'Jordan'</b>,<br />  craft: <b>'Full stack'</b>,<br />  loves: [<br />    <b>'Good systems'</b>,<br />    <b>'Useful products'</b><br />  ]<br />{'}'};</pre></div></div>
      <div className="mini-projects"><div><Code2 size={18} /><strong>Atlas workspace</strong><small>React · TypeScript</small></div><div><Github size={18} /><strong>Open source, open ideas</strong><small>Tools for better work</small></div></div>
    </> : bento ? <>
      <div className="mini-bento-grid"><div className="mini-bento-intro"><span>Designer, thinker, maker.</span><h3>A little curiosity.<br />A lot of possibility.</h3><p>I'm Maya. I make digital things feel human.</p><span className="mini-work-button">Let's talk <ArrowUpRight size={12} /></span></div><div className="mini-art mini-art-peach"><div className="sculpture sculpture-loop" /></div><div className="mini-bento-note"><span>Currently exploring</span><strong>Where useful<br />meets beautiful.</strong><ArrowUpRight size={20}/></div><div className="mini-art mini-art-lilac"><span className="mini-art-title">Field<br />notes.</span><div className="sculpture sculpture-sphere" /></div></div>
    </> : <>
      <div className="mini-professional-hero"><div><span className="mini-available"><i /> Available for new projects</span><h3>Thoughtful work.<br />Meaningful impact.</h3><p>I'm Alex, a product designer turning complex ideas into simple, human experiences.</p><span className="mini-work-button">View selected work <ArrowUpRight size={12} /></span></div><div className="mini-portrait-art"><span className="mini-portrait-letter">a.</span><div className="sculpture sculpture-arch"/><span className="mini-art-caption">Design is a way of seeing.</span></div></div>
      <div className="mini-section-label"><span>Selected work</span><span>2024 — 2026</span></div><div className="mini-projects"><div className="mini-art mini-art-sage"><strong className="mini-project-title">FORM<span>Brand & digital experience</span></strong><div className="sculpture sculpture-disc" /></div><div className="mini-art mini-art-sand"><strong className="mini-project-title">Good things.<span>Product strategy & design</span></strong><div className="sculpture sculpture-loop" /></div></div>
    </>}
    {expanded && <div className="mini-expanded-content"><div><span>About me</span><h4>{developer ? 'Good code starts with a better question.' : 'A considered approach to every project.'}</h4><p>This is a sample portfolio. Your introduction, experience, skills, and projects will take their place here when you build your own.</p></div><div><span>Experience</span><h4>{developer ? 'Senior Software Engineer' : 'Senior Product Designer'}</h4><p>Northstar Studio · 2022 — Present</p><h4>{developer ? 'Software Engineer' : 'Product Designer'}</h4><p>Fieldwork · 2019 — 2022</p></div><footer><span><MapPin size={13} /> Working everywhere.</span><span><Mail size={13} /> Let's make something great.</span></footer></div>}
  </div>;
}
