import { useState } from 'react';
import { Link, useLocation } from 'wouter';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronDown, Code2, FileText, Globe2, LayoutTemplate, Link2, LockKeyhole, Palette, Search, ShieldCheck, Sparkles, Upload } from 'lucide-react';
import { useListTemplates, getListTemplatesQueryKey } from '@workspace/api-client-react';
import { Button, Footer, MarketingNav, TemplateCard, type Template } from '@/components/folio-ui';
import { PortfolioMini } from '@/components/portfolio-mini';
import { readOnboardingDraft, saveOnboardingDraft } from '@/lib/folio-data';
import { OnboardingLayout } from '@/pages/onboarding';
import './marketing.css';

const previewTemplates: Template[] = [
  { id:'clean-professional', name:'Clean Professional', category:'Universal', description:'A clear introduction, considered details, and room for your best work.', premium:false, layout:'timeline' },
  { id:'developer-command-center', name:'Developer Command Center', category:'Technology', description:'A dark canvas for the systems you build and the projects you ship.', premium:true, layout:'terminal' },
  { id:'bento-professional', name:'Bento Professional', category:'Creative & Business', description:'An expressive, modular home for a wonderfully varied body of work.', premium:true, layout:'bento' },
];
const styleNames = ['Professional', 'Developer', 'Creative'];

function PortfolioShowcase() {
  const [style, setStyle] = useState(0);
  const reduced = useReducedMotion();
  return <div className="hero-showcase"><div className="showcase-grid" aria-hidden="true"/><div className="hero-resume-note"><div className="resume-icon"><FileText size={21}/></div><div><strong>My experience.pdf</strong><span>Your story starts here</span></div><CheckCircle2 size={17} className="text-emerald-600"/></div>
    <motion.div className="hero-browser" initial={{opacity:0,y:reduced ? 0 : 25,rotate:reduced ? 0 : -3}} animate={{opacity:1,y:0,rotate:0}} transition={{duration:.7,delay:.15,ease:[.2,.8,.2,1]}}><div className="hero-browser-bar"><div><i/><i/><i/></div><span><LockKeyhole size={9}/> folio / your-name</span><ArrowUpRight size={12}/></div><AnimatePresence mode="wait"><motion.div key={style} initial={{opacity:0,x:reduced ? 0 : 10}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:.22}}><PortfolioMini templateId={previewTemplates[style].id}/></motion.div></AnimatePresence></motion.div>
    <div className="hero-publish-note"><div><Globe2 size={20}/></div><span><strong>Ready for your next chapter</strong><small>One portfolio. One shareable link.</small></span><span className="publish-check"><Check size={13}/></span></div>
    <div className="showcase-style-switch" aria-label="Preview a portfolio style">{styleNames.map((name,i) => <button key={name} onClick={() => setStyle(i)} aria-pressed={style===i} className={style===i ? 'active' : ''}>{i===0 ? <LayoutTemplate size={13}/> : i===1 ? <Code2 size={13}/> : <Palette size={13}/>} {name}</button>)}</div><span className="showcase-caption">A few ways your story could look</span>
  </div>;
}

export function Landing() {
  const reduced = useReducedMotion();
  const [,navigate] = useLocation();
  const select = (template: Template) => { saveOnboardingDraft({templateId:template.id}); navigate('/onboarding/upload'); };
  return <><MarketingNav/><main id="main-content" className="marketing"><section className="folio-hero"><div className="hero-copy"><motion.div initial={{opacity:0,y:reduced ? 0 : 15}} animate={{opacity:1,y:0}} transition={{duration:.5}}><div className="hero-tag"><span><Sparkles size={13}/></span> A new home for your experience</div><h1>More than a resume.<br/>A space that’s<br/><span className="hero-final-word">entirely you.<svg viewBox="0 0 340 20" fill="none" aria-hidden="true"><path d="M5 12C90 1 207 2 332 8M24 18C122 10 201 9 290 13" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg></span></h1><p>Turn your experience into a portfolio you’re proud to share. Find your style, make it your own, and put your next opportunity one click away.</p><div className="hero-actions"><Link href="/onboarding/upload" className="folio-button folio-button-primary" data-testid="link-hero-start">Create my portfolio <ArrowUpRight size={17}/></Link><Link href="/templates" className="hero-secondary-link" data-testid="link-hero-templates">Explore the designs <ArrowRight size={15}/></Link></div><div className="hero-assurances"><span><Check size={14}/> Free to start</span><span><Check size={14}/> No coding needed</span><span><Check size={14}/> Your own link</span></div></motion.div></div><PortfolioShowcase/></section>
    <div className="audience-strip"><span>A space for every kind of talent</span><div>{['Developers','Designers','Consultants','Creators','Educators'].map((name,i) => <span key={name}>{i%2===0 ? <span className="audience-asterisk" aria-hidden="true">✳</span> : <span className="audience-circle" aria-hidden="true"/>}{name}</span>)}</div></div>
    <section className="marketing-section collection-section" id="templates"><div className="section-heading-row"><div><span className="section-kicker"><Palette size={15}/> Find your expression</span><h2>Good work deserves<br/>a great first impression.</h2></div><div><p>Different personalities. Different possibilities.<br/>Find a design that feels like you.</p><Link href="/templates" className="text-link">Explore all designs <ArrowUpRight size={16}/></Link></div></div><div className="template-grid">{previewTemplates.map(t => <TemplateCard key={t.id} template={t} onChoose={select}/>)}</div></section>
    <section id="how-it-works" className="how-section"><div className="marketing-section"><div className="section-heading-row"><div><span className="section-kicker"><Sparkles size={15}/> A little input. A big introduction.</span><h2>From your experience<br/>to your own corner of the web.</h2></div><p>We take care of the structure.<br/>You bring the story.</p></div><div className="how-grid"><div className="how-step"><div className="how-visual how-upload"><div className="how-document"><FileText size={28}/><span>My resume</span><i/><i/><i/><i/></div><span className="how-upload-icon"><Upload size={18}/></span></div><span className="step-number">01</span><h3>Bring your experience</h3><p>Start with your resume or add your details. Keep the parts of your story you want people to see.</p></div><div className="how-step"><div className="how-visual how-design"><div/><div/><div/><span><Palette size={19}/></span></div><span className="step-number">02</span><h3>Find your kind of beautiful</h3><p>Choose a design and refine your introduction. Preview it on desktop and mobile as you go.</p></div><div className="how-step"><div className="how-visual how-share"><div><Globe2 size={19}/><span>your-name / portfolio</span><CheckCircle2 size={18}/></div><span className="share-cursor"><ArrowUpRight size={28}/></span></div><span className="step-number">03</span><h3>Make your next connection</h3><p>Publish one simple link for your applications, social profiles, and conversations that matter.</p></div></div></div></section>
    <section className="marketing-section details-section"><div className="details-statement"><span className="section-kicker"><ShieldCheck size={15}/> Thoughtful by default</span><h2>Your career moves.<br/>Your portfolio<br/>moves with it.</h2><p>Build something that grows with you, without starting from scratch every time.</p><Link href="/onboarding/upload" className="text-link">Make your first draft <ArrowRight size={16}/></Link></div><div className="details-grid">{[{icon:Globe2,title:'A link that stays yours',text:'Update your work without changing the link you’ve already shared.'},{icon:LayoutTemplate,title:'Looks right, everywhere',text:'Thoughtfully designed for small screens, big screens, and everything between.'},{icon:PencilIcon,title:'Always room for an edit',text:'A new project, a new role, a better introduction. Keep your story current.'},{icon:ShieldCheck,title:'You choose what’s public',text:'Review your content before publishing. Unpublish whenever you need to.'}].map(({icon:Icon,title,text}) => <div key={title}><span className="detail-icon"><Icon size={20}/></span><h3>{title}</h3><p>{text}</p></div>)}</div></section>
    <section className="final-cta"><div className="cta-orbits" aria-hidden="true"><i/><i/><i/></div><div><span className="cta-tag">Your next chapter starts here</span><h2>You’ve done the work.<br/>Now let it open doors.</h2><Link href="/onboarding/upload" className="folio-button" data-testid="link-promise-signup">Build my portfolio <ArrowUpRight size={17}/></Link><p>Start free. Make it yours.</p></div></section></main><Footer/></>;
}
function PencilIcon({size = 20}: {size?:number}) { return <FileText size={size}/>; }

export function Templates({onboarding = false}: {onboarding?:boolean}) {
  const query=useListTemplates({query:{queryKey:getListTemplatesQueryKey(),retry:1,staleTime:60000}});
  const templates=(query.data || previewTemplates) as Template[];
  const [filter,setFilter]=useState('All designs');
  const [search,setSearch]=useState('');
  const [chosen,setChosen]=useState(readOnboardingDraft().templateId || '');
  const [,navigate]=useLocation();
  const filters=['All designs','Universal','Technology','Creative & Business'];
  const visible=templates.filter(t=>(filter==='All designs' || t.category===filter) && `${t.name} ${t.description} ${t.category}`.toLowerCase().includes(search.toLowerCase().trim()));
  const choose=(t:Template)=>{setChosen(t.id);saveOnboardingDraft({templateId:t.id});};
  const gallery=<><div className="library-toolbar"><div className="library-tabs" aria-label="Filter templates">{filters.map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)} data-testid={`button-filter-${f.toLowerCase().replaceAll(' ','-')}`}>{f}</button>)}</div><label className="library-search"><Search size={16}/><input aria-label="Search designs" placeholder="Find your style…" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{query.isError && <div className="library-connection-note" role="status">You can still explore these design previews. <button onClick={()=>query.refetch()}>Reconnect to the template library</button></div>}<p className="library-count" aria-live="polite">{visible.length} {visible.length===1?'design':'designs'} to make your own <span>All designs include a mobile layout</span></p><div className="template-grid">{visible.map(t=><TemplateCard key={t.id} template={t} selected={chosen===t.id} onChoose={choose}/>)}</div>{visible.length===0 && <div className="library-empty"><Search size={30}/><h3>No designs found</h3><p>Try another search or browse the full collection.</p><Button variant="outline" onClick={()=>{setFilter('All designs');setSearch('');}}>Show all designs</Button></div>}{chosen && <div className="selection-bar"><span><CheckCircle2 size={18}/><strong>{templates.find(t=>t.id===chosen)?.name || 'Your design'}</strong><span> selected</span></span><Button onClick={()=>navigate(onboarding?'/onboarding/preview':'/onboarding/upload')} data-testid="link-continue-templates">{onboarding?'Preview my portfolio':'Make it mine'} <ArrowRight size={15}/></Button></div>}</>;
  if(onboarding) return <OnboardingLayout current={3} eyebrow="Choose your design" title="Find a style that feels like you."><div className="onboarding-template-library">{gallery}</div></OnboardingLayout>;
  return <><MarketingNav/><main id="main-content" className="marketing-section library-page"><div className="library-title"><span className="section-kicker"><LayoutTemplate size={15}/> The design collection</span><h1>A first impression.<br/>A lasting expression.</h1><p>A home for your ideas, your experience, and whatever comes next.<br/>Preview every design. Publish the basic design for free.</p></div>{gallery}</main><Footer/></>;
}

const questions=[{q:'Can I build a portfolio for free?',a:'Yes. The basic design includes a shareable portfolio link and editing tools. You’ll need to sign in before publishing.'},{q:'Can I preview premium designs?',a:'Yes. Explore every design and try it with your content. Premium checkout is not enabled in this version, so only the basic design can be published.'},{q:'Can I connect my own domain?',a:'Custom-domain connection is planned. For now, publish using your portfolio’s included link. You can keep editing without changing that address.'},{q:'Can I change my portfolio after publishing?',a:'Yes. Update your content in the dashboard and save your changes. Your portfolio keeps the same link. You can also unpublish it.'}];
export function Pricing() {
  return <><MarketingNav/><main id="main-content" className="marketing-section pricing-page"><div className="library-title"><span className="section-kicker"><Sparkles size={15}/> Room to grow</span><h1>Start with your story.<br/>Make more of it.</h1><p>A simple place to begin, with more possibilities on the way.</p></div><div className="pricing-grid"><Plan name="Free" price="$0" note="Everything you need to make a start." features={['One published portfolio','Clean Professional design','A shareable portfolio link','Edit and update your content','Responsive desktop and mobile layouts']}/><Plan featured name="Studio" price="$12" note="More ways to express your professional identity." features={['Everything in Free','Premium portfolio designs','Custom-domain connection','Expanded portfolio insights','Priority support']}/></div><p className="pricing-note">Studio is a planned offering. Checkout and custom-domain connection are not available yet.</p><section className="faq-section"><h2>A few things you might be wondering.</h2><div>{questions.map(({q,a})=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section></main><Footer/></>;
}
export function Plan({name,price,note,features,featured=false}:{name:string;price:string;note:string;features:string[];featured?:boolean}) {
  return <article className={`pricing-card ${featured?'pricing-card-featured':''}`}><div className="pricing-card-top"><span className="pricing-icon">{featured?<Sparkles size={21}/>:<Globe2 size={21}/>}</span>{featured&&<span className="plan-soon">Coming soon</span>}</div><h2>{name}</h2><p>{note}</p><div className="plan-price">{price}<span>/ month</span></div><Link href={featured?'/templates':'/onboarding/upload'} className={`folio-button ${featured?'folio-button-outline':'folio-button-primary'}`} data-testid={`link-plan-${name.toLowerCase()}`}>{featured?'Preview premium designs':'Create my free portfolio'}<ArrowRight size={15}/></Link><div className="plan-includes">{featured?'Designed for your next chapter':'Your free plan includes'}</div><ul>{features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul></article>;
}
